const WALLET_TRANSACTION_TYPES = {
  TOP_UP: 'TOP_UP',
  WITHDRAW: 'WITHDRAW',
  BOOKING_PAYMENT: 'BOOKING_PAYMENT',
  BOOKING_REFUND: 'BOOKING_REFUND',
};

const WALLET_TRANSACTION_STATUS = {
  SUCCESS: 'success',
  FAILED: 'failed',
};

module.exports = {
  WALLET_TRANSACTION_TYPES,
  WALLET_TRANSACTION_STATUS,
};
